name: iou
description: "A new Flutter project."

publish_to: 'none'

version: 2.0.0+8

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  stack_appodeal_flutter: ^3.4.2
  feedback: ^3.1.0
  flutter_email_sender: ^7.0.0
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  dotted_border: ^2.1.0
  shared_preferences: ^2.5.2
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/listing/logo.png"
  min_sdk_android: 21
